FROM technolibre/erplibre-core:12.0

USER root

RUN apt update && \
        apt install -y  -y --no-install-recommends \
        build-essential \
        wget \
        python3-dev \
        python3-venv \
        python3-wheel \
        libxslt-dev \
        libzip-dev \
        libldap2-dev \
        libsasl2-dev \
        python3-setuptools \
        libpng16-16 \
        gdebi \
        && rm -rf /var/lib/apt/lists/* \
        && npm install -g rtlcss


ENV ADDONS_BASE_DIR /ERPLibre
ENV ENV=dev

# Copy entrypoint script and Odoo configuration file
COPY ./entrypoint.sh /
RUN  chmod +x /entrypoint.sh

# ENV REPO_MANIFEST_URL https://github.com/agileops/ERPLibre.git
