language: minimal

services:
  - docker

script:
  - docker build -t technolibre/erplibre-base:12.0 docker/base
  - docker build -t technolibre/erplibre:12.0 docker/main

after_success:
  - docker login --username mikefaille --password "${DOCKER_TOKEN}"
  - docker push technolibre/erplibre-base:12.0
  - docker push technolibre/erplibre:12.0
