---
- name: Exécuter apt upgrade sur tous les serveurs
  hosts: leChoixDuSysadmin
  become: yes

  tasks:
    - name: Mettre à jour la liste des paquets APT
      apt:
        update_cache: yes

    - name: Mettre à jour uniquement les paquets installés
      apt:
        upgrade: yes


