#!/usr/bin/env python3

import os
import sys
import subprocess

# Vérifier les arguments
if len(sys.argv) < 3:
    print("❌ Utilisation: ./playbook-adhoc <PLAYBOOK> <IP1> [<IP2> ...]")
    sys.exit(1)

PLAYBOOK = sys.argv[1]
TARGETS = sys.argv[2:]

# Générer le nom du fichier d'inventaire
inventaireDuSysadmin = f"./{PLAYBOOK}.hosts"

# Générer le contenu du fichier d'inventaire
choixDuSysadmin = "\n".join([f"{ip}" for ip in TARGETS])

inventory_content = f"""[leChoixDuSysadmin]
{choixDuSysadmin}
"""

# Écrire l'inventaire dans un fichier temporaire
with open(inventaireDuSysadmin, "w") as file:
    file.write(inventory_content)

print(f"✅ Fichier d'inventaire généré : {inventaireDuSysadmin}")

# Exécuter le playbook Ansible
command = f"ansible-playbook {PLAYBOOK}.yml -K -i {inventaireDuSysadmin} --private-key ~/.ssh/id_ed25519_ansible_Projet_KBR"
print(f"🚀 Exécution de : {command}")

try:
    subprocess.run(command, shell=True, check=True)
    print("✅ Playbook exécuté avec succès !")
except subprocess.CalledProcessError:
    print("❌ Erreur lors de l'exécution du playbook.")

# Ne pas supprimer le fichier d'inventaire pour une réutilisation éventuelle
print(f"📂 Le fichier d'inventaire {inventaireDuSysadmin} est conservé.")

