FROM technolibre/erplibre-core:12.0

USER root

RUN apt update && \
        apt install -y  -y --no-install-recommends \
        build-essential \
        wget \
        python3-dev \
        python3-venv \
        python3-wheel \
        libxslt-dev \
        libzip-dev \
        libldap2-dev \
        libsasl2-dev \
        python3-setuptools \
        libpng16-16 \
        gdebi \
        && rm -rf /var/lib/apt/lists/* \
        && npm install -g rtlcss

# RUN pip3 install -r https://raw.githubusercontent.com/odoo/odoo/12.0/requirements.txt --ignore-installed psycopg2  &&  pip3a cache purge

ENV ADDONS_BASE_DIR /ERPLibre
ENV ENV=dev

# Copy entrypoint script and Odoo configuration file
COPY ./entrypoint.sh /
RUN  chmod +x /entrypoint.sh

ENV ODOO_PREFIX /ERPLibre
ENV ODOO_EXEC_BIN $ODOO_PREFIX/odoo/odoo-bin


COPY repo_manifest_gen_org_prefix_path.py /usr/bin/
RUN chmod +x /usr/bin/repo_manifest_gen_org_prefix_path.py

USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]
