version: "3.3"
services:
    ERPLibre:
      image: test
      ports:
        - 8069:8069
      environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: odoo
        POSTGRES_DB: odoo
      depends_on:
        - db
      networks:
        - front
      command: odoo -c /etc/odoo/odoo.conf --without-demo=ALL -i base -d odoo

    db:
      image: postgres:12.3
      environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: odoo
        POSTGRES_DB: odoo
      networks:
        - front


networks:
  front:

    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
