[build-system]
requires = [ "poetry>=1.5.0",]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
py_version = 38

[tool.black]
line-length = 79
target-version = [ "py37",]

[tool.poetry]
name = "ERPLibre"
version = "1.6.0"
description = "Easy way to configure Odoo community"
license = "AGPL-3.0-or-later"
authors = [ "Mathieu Benoit <mathben@technolibre.ca>",]

[tool.poetry.dependencies]
python = ">=3.8.20,<3.9"
acme = "2.11.0"
aiohttp = "3.10.10"
aioshutil = "<1.2"
anyio = ">=3.5"
asn1crypto = "1.4.0"
astor = "^0.8.1"
avalara = "^25.7.1"
azure-identity = "1.13.0"
azure-storage-blob = "12.16.0"
babel = "2.9.1"
beautifulsoup4 = "^4.13.4"
bokeh = "2.4.2"
boto3 = ">=1.20.41"
cachetools = "5.5.2"
cadquery = "2.4.0"
cbor2 = "5.4.2"
chardet = "5.0.0"
click = "8.1.8"
cloudflare = "2.20.0"
coverage = "7.6.1"
cryptography = "3.4.8"
css-html-prettify = "^2.5.5"
cython = "^3.1.2"
decorator = "4.4.2"
dnspython = "2.6.1"
docutils = "0.16.0"
ebaysdk = "2.1.5"
email-validator = "^2.2.0"
emoji = "^2.14.1"
extract-msg = "0.36.1"
ezdxf = "1.1.4"
factur-x = "<=3.1"
feedparser = "6.0.10"
flake8 = "<6.0.0"
formio-data = "^2.1.1"
freezegun = "0.3.15"
future = "0.18.3"
geoip2 = "2.9.0"
geojson = "<3.0.0"
gevent = "20.9.0"
gitpython = "^3.1.45"
greenlet = "0.4.17"
hdbcli = "^2.25.29"
html2text = "2024.2.26"
idna = "2.8"
img2pdf = "^0.6.1"
iscompatible = "^0.1.1"
isort = "<5.12.0"
jinja2 = "2.11.3"
jira = "^3.8.0"
josepy = "1.14.0"
keystoneauth1 = "3.14.0"
libsass = "0.18.0"
lxml = "4.9.1"
mako = "1.2.2"
markupsafe = "1.1.0"
matplotlib = "3.7.5"
mpld3 = "0.5.7"
mysqlclient = "2.1.1"
num2words = "0.5.6"
numpy = "1.21.1"
numpy-financial = "<=1.0.0"
numpy-stl = "3.1.2"
oauthlib = "^3.3.1"
odoo-test-helper = "^2.1.1"
odoorpc = "^0.10.1"
ofxparse = "0.19"
openai = "^1.97.1"
openpyxl = "3.0.9"
openupgradelib = "^3.11.1"
ovh = "1.1.2"
packaging = "21.3"
pandas = "1.3.5"
paramiko = "^3.5.1"
passlib = "1.7.3"
pathspec = "^0.12.1"
pdf2image = "^1.17.0"
phonenumbers = "^9.0.10"
pillow = "10.3.0"
polib = "1.1.0"
prometheus-client = "0.11.0"
psutil = "5.9.0"
psycopg2 = "2.9.5"
py3o-formats = "^0.3"
py3o-template = "^0.10.0"
pycountry = "^24.6.1"
pydot = "1.4.1"
pyftpdlib = "^2.0.1"
pygithub = "^2.6.1"
pygments = "2.7.4"
pygount = "1.5.1"
pyjwt = "2.5.0"
pykcs11 = "^1.5.17"
pylint = "3.1.0"
pymssql = "<=2.2.5"
pyopenssl = "21.0.0"
pypdf = "^5.8.0"
pypdf2 = "1.27.9"
pyproj = "3.2.1"
pysaml2 = "7.2.1"
pyserial = "3.4"
pysftp = "^0.2.9"
python-chess = "^1.999"
python-dateutil = "2.7.3"
python-git = "^2018.2.1"
python-jose = "3.4.0"
python-json-logger = "0.1.5"
python-keystoneclient = "3.22.0"
python-ldap = "3.4.0"
python-magic = "^0.4.27"
python-slugify = "^8.0.4"
python-stdnum = "1.13"
python-swiftclient = "3.9.0"
python-u2flib-server = "^5.0.1"
pytz = ">=2022.7"
pyusb = "1.0.2"
pyyaml = "6.0"
pyzbar = "^0.1.9"
qrcode = "6.1"
redis = "3.2.1"
regex = "2022.3.2"
reportlab = "3.6.5"
requests = "2.28.1"
requests-oauthlib = "^2.0.0"
requests-toolbelt = "^1.0.0"
rjsmin = "1.1.0"
schwifty = "2024.4.0"
selenium = "4.25.0"
sentry-sdk = "<=1.9.0"
setuptools = "65.5.1"
shapely = "1.8.5"
simplejson = "3.16.0"
sphinx = "4.3.2"
sphinx-intl = "2.2.0"
sphinx-rtd-theme = "1.3.0"
statsd = "3.2.1"
toml = "^0.10.2"
tqdm = "^4.67.1"
unicodecsv = "^0.14.1"
unidecode = "^1.4.0"
urllib3 = ">=1.26.13"
uvloop = "^0.21.0"
validators = "0.24.0"
vobject = "0.9.6.1"
voicent-python = "^1.0"
webcolors = "24.8.0"
websocket-client = "^1.8.0"
werkzeug = "0.16.1"
wheel = "^0.45.1"
win-unicode-console = "^0.5"
xlrd = "1.2.0"
xlsxwriter = "1.1.2"
xlwt = "1.3.0"
xmlformatter = "^0.2.8"
xmlrunner = "^1.7.7"
xmlschema = "3.4.5"
zeep = "3.4.0"
zipp = ">=3.6.0"
zxcvbn = "^4.5.0"

[tool.poetry.dev-dependencies]
websocket_client = "^1.1.0"

[tool.poetry.dependencies.black]
git = "https://github.com/psf/black.git"
rev = "22.3.0"

[tool.poetry.dependencies.pylint-odoo]
git = "https://github.com/oca/pylint-odoo.git"
rev = "v9.1.3"
