[build-system]
requires = [ "poetry>=1.5.0",]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
py_version = 37

[tool.black]
line-length = 79
target-version = [ "py37",]

[tool.poetry]
name = "ERPLibre"
version = "1.6.0"
description = "Easy way to configure Odoo community"
license = "AGPL-3.0-or-later"
authors = [ "Mathieu Benoit <mathben@technolibre.ca>",]

[tool.poetry.dependencies]
python = ">=3.7.16,<3.8"
acme = "2.6.0"
aiohttp = "3.8.6"
aioshutil = "<1.2"
altair = "5.0.1"
argcomplete = "3.1.1"
astor = "^0.8.1"
avalara = "^25.7.1"
azure-identity = "1.15.0"
azure-storage-blob = "12.19.0"
babel = "2.9.1"
beautifulsoup4 = "^4.13.4"
bokeh = "1.1.0"
boto3 = "1.33.13"
cachetools = ">=2.0.1"
chardet = "5.0.0"
click = "8.1.8"
cloudflare = "3.0.1"
code-writer = "1.1.1"
coverage = "7.2.7"
cryptography = "39.0.1"
css-html-prettify = "^2.5.5"
cubiscan = "^0.0.3"
cython = "3.0.10"
decorator = "4.3.0"
dicttoxml = "^1.7.16"
dnspython = "2.3.0"
docutils = "0.17.1"
ebaysdk = "2.1.5"
email-validator = "2.0.0"
emoji = "^2.14.1"
endesive = "^2.19.1"
extract-msg = "0.36.1"
factur-x = "3.6"
feedparser = "6.0.10"
flake8 = "<6.0.0"
formio-data = "^2.1.1"
furo = "2021.2.21b25"
future = "0.18.3"
geojson = "<3.0.0"
gevent = "1.5.0"
gitpython = "^3.1.45"
giturlparse = "0.10.0"
greenlet = "0.4.14"
html2text = "2016.9.19"
humanize = "4.6.0"
iscompatible = "^0.1.1"
isort = "<5.12.0"
jinja2 = "2.11.3"
jira = "2.0.0"
josepy = "1.14.0"
keystoneauth1 = "3.14.0"
libsass = "0.17.0"
lxml = "4.9.1"
mako = "1.2.2"
markupsafe = "1.1.0"
matplotlib = "3.3.4"
mmg = "1.0.3"
mock = "2.0.0"
mpld3 = "0.3"
mysqlclient = "2.1.1"
num2words = "0.5.6"
numpy = "1.21.1"
numpy-financial = "<=1.0.0"
oauthlib = "3.2.2"
odoorpc = "^0.10.1"
ofxparse = "0.19"
olefile = "0.47"
openpyxl = "3.1.3"
ovh = "1.1.2"
pandas = "1.3.5"
paramiko = "3.5.1"
passlib = "1.7.1"
pathspec = "0.11.2"
pdf2image = "^1.17.0"
phantomjs = "^1.4.1"
phonenumbers = "^9.0.12"
pillow = "9.3.0"
polib = "1.1.0"
premailer = "^3.10.0"
prometheus-client = "0.11.0"
psutil = "5.9.0"
psycopg2 = "2.9.5"
py3o-formats = "^0.3"
py3o-template = "^0.10.0"
pycountry = "22.3.5"
pydot = "1.4.1"
pyftpdlib = "^2.0.1"
pygments = "2.7.4"
pygount = "1.2.1"
pyjwt = "2.5.0"
pylint-odoo = "8.0.19"
pymssql = "2.3.0"
pyopenssl = "<23"
pyparsing = "2.2.0"
pypdf = "4.3.1"
pypdf2 = "1.27.9"
pyproj = "3.2.1"
pysaml2 = "7.3.1"
pyserial = "3.4"
pysftp = "^0.2.9"
python-chess = "<0.24"
python-dateutil = "2.7.3"
python-git = "^2018.2.1"
python-jose = "3.3.0"
python-json-logger = "0.1.5"
python-keystoneclient = "3.22.0"
python-ldap = "3.1.0"
python-magic = "^0.4.27"
python-pptx = "0.6.23"
python-slugify = "^8.0.4"
python-stdnum = "1.20"
python-swiftclient = "3.9.0"
python-u2flib-server = "^5.0.1"
pytz = ">=2022.7"
pyusb = "1.0.2"
pyyaml = "6.0"
pyzbar = "^0.1.9"
qrcode = "6.1"
randomwords = "^0.4.0"
raven = "^6.10.0"
redis = "2.10.5"
reportlab = "3.6.5"
requests = "2.28.1"
requests-mock = "^1.12.1"
responses = "0.23.1"
selenium = "4.11.2"
setuptools = "65.5.1"
shapely = "1.8.5"
simplejson = "^3.20.1"
sphinx = "3.0"
sphinx-intl = "2.2.0"
sphinx-rtd-theme = "1.2.2"
sqlalchemy = "2.0.36"
sqlparse = "0.4.4"
statsd = "3.2.1"
suds = "^1.2.0"
toml = "^0.10.2"
tqdm = "^4.67.1"
unidecode = "^1.4.0"
urllib3 = ">=1.26.13"
uvloop = "0.17.0"
validators = "0.20.0"
vobject = "0.9.6.1"
voicent-python = "^1.0"
webcolors = "1.13"
websocket-client = "1.6.1"
werkzeug = "0.16.1"
wheel = "0.42.0"
win-unicode-console = "^0.5"
xlrd = "1.1.0"
xmlformatter = "^0.2.8"
xmlschema = "2.5.1"
xmltodict = "^0.14.2"
zeep = "4.2.1"
zipp = ">=3.6.0"
zxcvbn = "^4.5.0"

[tool.poetry.dev-dependencies]
websocket_client = "^1.1.0"

[tool.poetry.dependencies.black]
git = "https://github.com/psf/black.git"
rev = "22.3.0"

[tool.poetry.dependencies.wechatpy]
extras = [ "cryptography",]
version = "^1.8.18"
