[build-system]
requires = [ "poetry>=1.8.3",]
build-backend = "poetry.masonry.api"

[tool.isort]
profile = "black"
py_version = 310

[tool.black]
line-length = 79
target-version = [ "py37",]

[tool.poetry]
name = "ERPLibre"
version = "1.6.0"
description = "Easy way to configure Odoo community"
license = "AGPL-3.0-or-later"
authors = [ "Mathieu Benoit <mathben@technolibre.ca>",]

[tool.poetry.dependencies]
python = ">=3.10.18,<3.11"
asana = "^5.2.1"
asn1crypto = "^1.5.1"
astor = "^0.8.1"
avalara = "^25.7.1"
azure-identity = "^1.24.0"
azure-storage-blob = "^12.26.0"
babel = "2.9.1"
base64io = "^1.0.3"
beautifulsoup4 = "^4.13.4"
bokeh = "3.4.1"
boto3 = "^1.40.11"
cachetools = "5.5.2"
chardet = "4.0.0"
countryinfo = "^0.1.2"
cryptography = "3.4.8"
cssselect = "^1.3.0"
cybersource-rest-client-python = "0.0.56"
cython = "^3.1.3"
decorator = "4.4.2"
dnspython = "^2.7.0"
docutils = "0.17"
dropbox = "^12.0.2"
ebaysdk = "2.1.5"
email-validator = "^2.2.0"
endesive = "<=2.18.5"
ezdxf = "^1.4.2"
factur-x = "^3.8"
filetype = "^1.2.0"
firebase-admin = "^7.1.0"
formio-data = "^2.1.1"
freezegun = "0.3.15"
fsspec = ">=2024.5.0"
gdown = "^5.2.0"
geocoder = "^1.38.1"
geoip2 = "2.9.0"
geojson = "^3.2.0"
geopy = "^2.4.1"
gevent = "23.9.0"
gitpython = "^3.1.45"
googletrans-py = "4.0.0"
greenlet = "3.2.1"
httpagentparser = "^1.9.5"
hubspot-api-client = "10.0.0"
idna = "2.10"
img2pdf = "^0.6.1"
jinja2 = "2.11.3"
libsass = "0.20.1"
linkedin = "^0.1.5"
lxml = "4.6.5"
mako = "^1.3.10"
markupsafe = "1.1.1"
matplotlib = "^3.10.5"
mechanize = "^0.4.10"
meteostat = "^1.7.4"
mpld3 = "0.5.10"
mysql-connector-python = "^9.4.0"
nextcloud-api-wrapper = "^0.2.3"
num2words = "0.5.13"
numpy = ">=1.15"
numpy-financial = "<=1.0.0"
numpy-stl = "^3.2.0"
odoorpc = "^0.10.1"
ofxparse = "0.21"
openai = "^1.99.9"
opencv-python = "^4.12.0.88"
openpyxl = "^3.1.5"
openupgradelib = "^3.11.1"
pandas = ">=0.25.3"
paramiko = "<4"
passlib = "1.7.4"
pathspec = "^0.12.1"
pdf2image = "^1.17.0"
pdfminer = "^20191125"
phonenumbers = "^9.0.12"
pillow = "10.3.0"
plotly = "5.22.0"
polib = "1.1.1"
pre-commit = "^4.3.0"
printnodeapi = "^0.2.0"
prometheus-client = "^0.22.1"
psutil = "5.8.0"
psycopg2 = "2.9.2"
py-asterisk = "^0.5.18"
py3dns = "^4.0.2"
py3o-formats = "^0.3"
py3o-template = "^0.10.0"
pycountry = "^24.6.1"
pydevd-odoo = "^1.2.2"
pydot = "1.4.2"
pygithub = "^2.7.0"
pyjwt = "^2.10.1"
pyncclient = "^0.7"
pyopenssl = "20.0.1"
pypdf = "^6.0.0"
pypdf2 = "1.26.0"
pysaml2 = "^7.5.2"
pyserial = "3.5"
pysftp = "^0.2.9"
pytesseract = "^0.3.13"
python-barcode = "^0.15.1"
python-dateutil = ">=2.8.2"
python-jose = "^3.5.0"
python-json-logger = "^3.3.0"
python-ldap = "3.4.0"
python-resize-image = "^1.1.20"
python-slugify = "^8.0.4"
python-stdnum = "1.17"
pytz = "^2025.2"
pyusb = "1.0.2"
pyyaml = "^6.0.2"
pyzbar = "^0.1.9"
pyzk = "^0.9"
qrcode = "7.3.1"
redis = "^6.4.0"
reportlab = "3.6.5"
requests = "2.30.0"
requests-toolbelt = "^1.0.0"
rjsmin = "1.1.0"
roulier = "^1.1.1"
schwifty = "2024.4.0"
sentry-sdk = "<=1.9.0"
setuptools = "65.5.1"
shapely = "^2.1.1"
spacy = "3.8.2"
speechrecognition = "3.10.0"
sqlalchemy = "^2.0.43"
statsd = "^4.0.1"
telesign = "^2.3.1"
tldextract = "^5.3.0"
tweepy = "^4.16.0"
twilio = "^9.7.1"
unidecode = "^1.4.0"
urllib3 = "1.26.5"
validate-email = "^1.3"
vobject = "0.9.6.1"
vonage = "^4.6.0"
vonage-verify-v2 = "1.1.4"
werkzeug = "2.0.2"
xlrd = "1.2.0"
xlsxwriter = "1.4.5"
xlwt = "1.3.0"
xmltodict = "0.13.0"
zeep = "4.1.0"

[tool.poetry.dev-dependencies]
websocket_client = "^1.1.0"

[tool.poetry.dependencies.black]
git = "https://github.com/psf/black.git"
rev = "24.8.0"
