#!/usr/bin/env python
# dict config contains information about repository of original source
# level 1: website of git
# level 2: entity, organization, user
# level 3: project name
config = {
    "github.com": {
        "odoo": [
            "odoo",
        ],
    }
}
config_addons = {
    "github.com": {
        "MathBenTech": [
            "development",
            "odoo-business-spending-management-quebec-canada",
            "scrummer",
        ],
        "muk-it": [
            "muk_base",
            "muk_dms",
            "muk_docs",
            "muk_misc",
            "muk_quality",
            "muk_web",
            "muk_website",
        ],
        "Numigi": [
            "odoo-base-addons",
            "odoo-entertainment-addons",
            "odoo-git-addons",
            "odoo-hr-addons",
            "odoo-partner-addons",
            "odoo-product-addons",
            "odoo-project-addons",
            "odoo-purchase-addons",
            "odoo-stock-addons",
            "odoo-survey-addons",
            "odoo-timesheet-addons",
            "odoo-web-addons",
        ],
        "OCA": [
            "account-analytic",
            "account-budgeting",
            "account-closing",
            "account-consolidation",
            "account-financial-reporting",
            "account-fiscal-rule",
            "account-invoicing",
            "account-invoice-reporting",
            "account-payment",
            "account-reconcile",
            "apps-store",
            "bank-payment",
            "bank-statement-import",
            "brand",
            "business-requirement",
            "commission",
            "community-data-files",
            "connector-telephony",
            "contract",
            "credit-control",
            "currency",
            "data-protection",
            "donation",
            "e-commerce",
            "edi",
            "event",
            "helpdesk",
            "hr",
            "knowledge",
            "l10n-canada",
            "maintenance",
            "management-system",
            "manufacture",
            "margin-analysis",
            "mis-builder",
            "multi-company",
            "partner-contact",
            "pos",
            "product-attribute",
            "product-pack",
            "product-variant",
            "project",
            "project-reporting",
            "purchase-workflow",
            "queue",
            "reporting-engine",
            "sale-workflow",
            "server-auth",
            "server-brand",
            "server-env",
            "server-tools",
            "server-ux",
            "social",
            "stock-logistics-warehouse",
            "timesheet",
            "web",
            "website",
            "wms",
        ],
        "odooaktiv": [
            "QuotationRevision",
        ],
        "openeducat": [
            "openeducat_erp",
        ],
        "Smile-SA": [
            "odoo_addons",
        ],
    }
}
